### ISSUE TITLE
Unable to create a mirror for GarageBand loops

### ISSUE THREAD

**Issue by nixaura** [carlashley/loopdown#2]
**Describe the bug**
Receive the error shown below trying to mirror GarageBand Mandatory/Optional loops:

`loopdown: error: --discover-plists-range not allowed without argument: --discovery-plists`

The arguments I'm passing to the binary are:

`./loopdown -a garageband -m -o --create-mirror /Users/TestCapture/Desktop/GB_Downloads`

**Which macOS Version?**
Output of `sw_vers`:

(Apple M1 iMac)
ProductName:		macOS
ProductVersion:		13.4.1
BuildVersion:		22F82

**Additional context**

```
/usr/local/bin/python3 --version
Python 3.11.4
```

**Comment by carlashley** [comment]
Please check [v1.0.20230706](https://github.com/carlashley/loopdown/releases/tag/v1.0.20230706) and see if this is resolved.

**Comment by staze** [comment]
Was seeing same issue, does seem resolved in [v1.0.20230706](https://github.com/carlashley/loopdown/releases/tag/v1.0.20230706)
