### ISSUE TITLE
Install Failure - Does not accept guided string of agruments

### ISSUE THREAD

**Issue by JDUBZzz** [carlashley/loopdown#3]
**Which `loopdown` version?**
- 1.0.20230621
- 1.0.20230706

**What applications are you installing packages for (delete those that don't apply)?**
- :white_check_mark: GarageBand (version: )
- :white_check_mark: Logic Pro (version: )
- :white_check_mark: MainStage 3 (version: )

**Are the packages being installed for the first time, or an upgrade?**
- :white_check_mark: First Time

**Which packages are installed but still prompt to be installed?**
Please include the folder path and package name including the file extension; for example:
- N/A

**Is the `--pkg-server` argument being used?**
- :white_check_mark: No

**If the `--pkg-server` argument has been used, have the packages been refreshed within the last week?**
-N/A

**Is the `--cache-server` argument being used?**
- :white_check_mark: No

**If the `--cache-server` has been used, has `loopdown` been run on one Mac to pre-warm the cache?**
-N/A

Has the `--log-level debug` argument and parameter been used?
If `loopdown` has been run with `--log-level debug`, please attach the output of the log run.
Log files are stored in `/Users/Shared/loopdown`; the most recent log will be `/Users/Shared/loopdown/loopdown.log`
- :white_check_mark: No

**Which macOS Version?**
- 13.4.1

**Overview of Issue**
Loopdown versions 1.0.20230621 or 1.0.20230706 fail to run. I am using the following string of arguments and am receiving this output:

_MacBook-Air:bin root# ./loopdown --app 'all' --mandatory --optional --install
['-m/--mandatory', '-o/--optional']
usage: loopdown [-h] [--advanced-help] [--version] [--log-level [level]] [-n] [-a [app] [[app] ...] | -p [plist] [[plist] ...]] [-m] [-o] [-f] [-i] [-s]
                [--create-mirror [path]] [--cache-server server] [--pkg-server [server]] [--discover-plists]
loopdown: error: argument -i/--install: not allowed without: -m/--mandatory and/or -o/--optional_

I receive the same error when using the shortened arguments as well as removing the quotations from the for the app string. 

I do not see this issue when running the same set of arguments in  v1.0.20230531. Am I missing additional arguments?

**Comment by carlashley** [comment]
Please check https://github.com/carlashley/loopdown/releases/tag/v1.0.20230726 resolves this for you.
