### ISSUE TITLE
No packages found for logicpro

### ISSUE THREAD

**Issue by staze** [carlashley/loopdown#4]
**Describe the bug**
Trying to download Mandatory packages for Logic Pro results in 
loopdown -m -a logicpro --create-mirror /Users/Shared/logicpro-mandatory 
Processing content for: 'logicpro' via 'https://audiocontentdownload.apple.com'
No packages found; there may be no packages to download/install or no application/s installed

Does same for optional.

**Comment by staze** [comment]
maybe this is an apple issue and there are no longer dedicated Logic Loops... the old appleloops program does same thing, just comes back with nothing found.

**Comment by carlashley** [comment]
You can't use the `-a` flag to create a mirror if the application isn't installed on the Mac that `loopdown` is used on.

Try using `loopdown --discover-plists` then find the most recent plist in the output and use the `-p` flag.

For example:
```
[jappleseed@infiniteloop]:loopdown # ./loopdown --discover-plists -a logicpro
Discovering property list files for 'logicpro'
Found property list file: 'logicpro1021.plist'
Found property list file: 'logicpro1022.plist'
Found property list file: 'logicpro1023.plist'
Found property list file: 'logicpro1030.plist'
Found property list file: 'logicpro1032.plist'
Found property list file: 'logicpro1040.plist'
Found property list file: 'logicpro1042.plist'
Found property list file: 'logicpro1050.plist'
Found property list file: 'logicpro1070.plist'
Found property list file: 'logicpro1075.plist'
Found property list file: 'logicpro1078.plist'
Found property list file: 'logicpro1080.plist'
[jappleseed@infiniteloop]:loopdown # ./loopdown -n -m -p logicpro1080.plist --create-mirror /Users/Shared/logicpro-mandatory
```

**Comment by staze** [comment]
Hey @carlashley this makes sense. I did try a discover discover-plists but it didn't seem to change anything... oh, you have to then point at it... got it. 

Will give that a shot. Thanks!

**Comment by staze** [comment]
okay, that does seem to work. It won't install without logicpro installed though... which guessing by design. We reached out to Apple about this few years back and they indicated there was no licensing issue installing Logic Pro loops for use with Garageband... is that the concern with not allowing install without logicpro installed?

**Comment by carlashley** [comment]
From what I've seen, most of the loops are used across all the three apps differently, and many many years ago when Apple sold loops in a DVD/CD bundle, they would work across Logic Pro/GarageBand.

If you did happen to have Logic Pro installed on the Mac you were creating a mirror on, it _should_ work with the `-a` argument and the relevant app as the parameter for that argument; it's just flagging the script to check if the relevant property list file containing the information about the loops is present in the app bundle which needs to be in `/Applications`.

The packages that Apple provides for the install of the loops contain an install check script to determine if any of the three apps are installed, and if they aren't, then the install exits. `loopdown` and the predeceasing `appleloops` never took steps to bypass that.

**Comment by staze** [comment]
Hi @carlashley, sorry I wasn't clear. Not trying to install on machines that don't have ANY of the apps. We have faculty that request the Logic loops for use with Garageband. Since Apple said this wasn't an issue legally (this took a while), I'm curious if we could add a flag, or otherwise allow installing the logic loops without logic installed. As it is, the loopdown app throws an error saying -i isn't allowed with -p. 

Thanks!

**Comment by carlashley** [comment]
No, I won't be implementing that.

**Comment by staze** [comment]
Bummer, okay. Does mean we have to just mirror it all then install “manually”. I would ask you to consider it at some point. Not asking to bypass any of the checks in the pkgs, or potentially break any licensing (edu contacts at apple said this was okay, but I admit, it was never anything we got their legal department to weigh on). Alternatively we install logic, install packages via loopdown, then remove logic. :/ 

anywho, thank you for your time! Tool is great!
