### ISSUE TITLE
Custom plist for specific loops packages

### ISSUE THREAD

**Issue by staze** [carlashley/loopdown#6]
Trying to see if we can target specific logic loops, so downloading the plist logicpro1080.plist and then removing everything but the section I want (Legacy, which is item 19 under //Root/Content/en/) from the plist, then pointing loopdown at that with 

sudo ./loopdown -o --plist ./logicpro1080_test.plist -n --create-mirror /Users/Shared/

Results in python errors. Is this something that should work?

**Comment by carlashley** [comment]
You're probably breaking the property list file such that it is no longer a valid plist file, or if it is a valid plist file, the file no longer has the correct key/value structure that is expected. Either way this is not something that this tool supports or will support.
