### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by rvgit3** [carlashley/loopdown#7]
**Describe the bug**
I get this error when trying to run loopdown. Packaging is installed. Any ideas?

**Which macOS Version?**
Output of `sw_vers`: 13.6.3

**Additional context**

**Comment by carlashley** [comment]
You may need to have the `packaging` module installed, this is used for version checks.
It can be installed following instructions here: https://pypi.org/project/packaging/

As far as I know, this _should_ be included in the pre-built frozen zip bundle, I'll have a look at this.

**Comment by carlashley** [comment]
This should be resolved in this release - https://github.com/carlashley/loopdown/releases/tag/1.0.20240102
