### ISSUE TITLE
Feature Request - Update Existing Mirror

### ISSUE THREAD

**Issue by kluppy** [carlashley/loopdown#8]
When using the `--create-mirror` option, is it possible to have loopdown test if the package already exists on the mirror before downloading?
I would like to automate running loopdown regularly to keep my mirror up to date but I would prefer not to download the 890 logic packages every time.

Thank you for the very useful tool :-)

**Comment by carlashley** [comment]
Apple have been known to update existing package contents to resolve issues with the installer or update the content of the package. There is no way to reliably determine if this is the case without downloading the package and inspecting it, at which point you've downloaded it anyway.

Using the file size is not as straight forward either, as the file size reported by the remote server compared to file size information within the property list files does not always correlate in a 1:1 manner.

It's something that I'd like to avoid doing as well, but can't unless Apple start including a more reliable mechanism in the property list files to determine the package is different.
